{
 "title": "Sample Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "50P response time of endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(\"service.name\", \"http.method\", \"http.route\", le) (rate({\"http.server.duration_milliseconds_bucket\", \"http.route\"!=\"\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95P response time of endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(\"service.name\", \"http.method\", \"http.route\", le) (rate({\"http.server.duration_milliseconds_bucket\", \"http.route\"!=\"\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate in Calling dependencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (\"net.peer.name\",\"http.status_code\") (rate({\"http.client.duration_milliseconds_count\", \"http.status_code\"!=\"200\", \"service.name\"=\"service-dicer\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reqeust Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (\"net.peer.name\",\"http.route\") (rate({\"http.client.duration_milliseconds_count\",\"service.name\"=\"service-dicer\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}