extensions:
  health_check:
    endpoint: 127.0.0.1:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector-metrics
          scrape_interval: 10s
          static_configs:
            - targets: ["127.0.0.1:8888"]
        - job_name: grafana-metrics
          scrape_interval: 10s
          static_configs:
            - targets: ["grafana:3000"]

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 10
  batch:
    send_batch_size: 8192
    timeout: 1s
    send_batch_max_size: 0
  resource:
    attributes:
      - action: insert
        key: service.name
        value: grafana

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp
    encoding: proto
    tls:
      insecure: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
  debug:
    verbosity: detailed
    sampling_initial: 2
    sampling_thereafter: 200

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/prometheus] # prometheusremotewrite
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp/loki]
  extensions: [health_check]
  telemetry:
    resource:
      service.name: grafana-opentelemetry/metrics
      author: monitoriginartist
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 127.0.0.1
                port: 8888
                with_resource_constant_labels:
                  included:
                    - service.name
                    - author
    logs:
      level: debug
      encoding: json
